//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace INNIM_1._2.AppData
{
    using System;
    using System.Collections.Generic;
    
    public partial class zakazi_programista
    {
        public int nomer_zakaza { get; set; }
        public Nullable<int> id_zakaza { get; set; }
        public Nullable<int> id_programmista { get; set; }
        public Nullable<System.DateTime> date_prinatia { get; set; }
        public string status { get; set; }
    
        public virtual programmisti programmisti { get; set; }
        public virtual zakazi zakazi { get; set; }
    }
}
