//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace INNIM_1._2.AppData
{
    using System;
    using System.Collections.Generic;
    
    public partial class zakazi
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public zakazi()
        {
            this.zakazi_programista = new HashSet<zakazi_programista>();
        }
    
        public int id_zakaza { get; set; }
        public Nullable<int> id_client { get; set; }
        public string info { get; set; }
        public Nullable<System.DateTime> date_create { get; set; }
        public Nullable<decimal> cost { get; set; }
    
        public virtual clients clients { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<zakazi_programista> zakazi_programista { get; set; }
    }
}
